# Generated by Django 6.0 on 2025-12-06 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('codigo_interno', models.CharField(help_text='Código manual o PLU (Ej: PROD-001)', max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('FISICO', 'Producto Físico'), ('SERVICIO', 'Servicio (Copia, Impresión)'), ('ANCHETA', 'Ancheta / Kit')], default='FISICO', max_length=10)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(default='UND', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaAncheta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('producto_hijo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('producto_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Ingrediente de Ancheta',
                'verbose_name_plural': 'Ingredientes de la Ancheta',
                'unique_together': {('producto_padre', 'producto_hijo')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='componentes',
            field=models.ManyToManyField(related_name='parte_de_kits', through='inventario.RecetaAncheta', to='inventario.producto'),
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=5, help_text='Alerta cuando baje de esta cantidad en esta sede')),
                ('ubicacion', models.CharField(blank=True, help_text='Ej: Pasillo 3, Estante A', max_length=50)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='inventario.producto')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='inventario.sede')),
            ],
            options={
                'verbose_name_plural': 'Inventarios / Existencias',
                'unique_together': {('producto', 'sede')},
            },
        ),
    ]
