# Generated by Django 6.0 on 2025-12-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_movimientoinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo al momento de la compra', max_digits=10, null=True),
        ),
    ]
