# Generated by Django 6.0 on 2026-01-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_movimientoinventario_costo_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(help_text='Coloca el nombre de la categoria del producto', max_length=100, unique=True),
        ),
    ]
