# Generated by Django 6.0 on 2026-01-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada / Compra'), ('SALIDA', 'Salida / Ajuste / Pérdida'), ('TRASLADO', 'Traslado entre Sedes'), ('VENTA', 'Venta al Público')], max_length=10),
        ),
    ]
