# Generated by Django 6.0 on 2026-01-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_detalleventacomponente'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='id_agrupador_kit',
            field=models.CharField(blank=True, help_text='UUID para agrupar items de una misma ancheta', max_length=50, null=True),
        ),
    ]
