# Generated by Django 6.0 on 2026-01-16 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_detalleventa_id_agrupador_kit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleVentaComponente',
        ),
    ]
