# Generated by Django 6.0 on 2026-01-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_delete_detalleventacomponente'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='porcentaje_comision',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de comisión/margen aplicado (especialmente para anchetas)', max_digits=5),
        ),
    ]
