# Generated by Django 6.0 on 2026-06-13 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_detalleventa_porcentaje_comision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo del producto al momento de la venta', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='anulada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venta',
            name='anulada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_anuladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='motivo_anulacion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
