# Generated by Django 6.0 on 2025-12-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('EMPLEADO', 'Empleado')], default='EMPLEADO', max_length=15),
        ),
    ]
